# Generated by Django 4.2.5 on 2023-11-06 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prjwk_contents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('uid', models.AutoField(db_column='UID', primary_key=True, serialize=False)),
                ('username', models.CharField(db_column='USERNAME', max_length=45)),
                ('userid', models.CharField(db_column='USERID', max_length=45)),
                ('userpw', models.CharField(db_column='USERPW', max_length=45)),
                ('useremail', models.CharField(blank=True, db_column='USEREMAIL', max_length=45, null=True)),
                ('phonenumber', models.CharField(blank=True, db_column='PHONENUMBER', max_length=45, null=True)),
            ],
            options={
                'db_table': 'user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VideoBusan',
            fields=[
                ('vid', models.AutoField(primary_key=True, serialize=False)),
                ('contents_path', models.CharField(blank=True, max_length=100, null=True)),
                ('contents_name', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'video_busan',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VideoSeoul',
            fields=[
                ('vid', models.AutoField(db_column='VId', primary_key=True, serialize=False)),
                ('contents_path', models.CharField(blank=True, max_length=100, null=True)),
                ('contents_name', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'video_seoul',
                'managed': False,
            },
        ),
    ]
